#saleServerPath: PlaceholderValue #TODO: Bonus

server:
  port: 8083

spring:
  session:
    store-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

eureka:
  client:
    enabled: false

management:
  health:
    rabbit:
      enabled: false