spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

zuul:
  routes:
    book-server:
      path: /book-server/**
    sale-server:
      path: /sale-server/**
    user-server:
      path: /user-server/**
    news-server:
      path: /news-server/**
  sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  sessions: ALWAYS