spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

zuul:
  routes:
    producer-server:
      path: /producer-server/** #FIXME
    consumer-server:
      path: /consumer-server/** #FIXME
  sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  sessions: ALWAYS