server:
  port: 8082

spring:
  application:
    name: book-server
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"
  session:
    store-type: hash_map #TODO: Investigate if this breaks auth

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  sessions: NEVER