bookServerPath: PlaceholderValue
sellerServerPath: PlaceholderValue

server:
  port: 8082

spring:
  session:
    store-type: none

eureka:
  client:
    enabled: false

management:
  health:
    rabbit:
      enabled: false