server:
  port: 8084

spring:
  application:
    name: news-server
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"
  rabbitmq:
    host: localhost
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  sessions: NEVER